### ISSUE TITLE
Does it work with Vaadin 7.1.7?

### ISSUE THREAD

**Issue by fancellu** [jouni/Animator#13]
I see comments about error:

Widgetset does not contain implementation for org.vaadin.jouni.animator.server.AnimatorProxy

Does it work now?

Thanks.

**Comment by jouni** [comment]
I haven't personally tested with 7.1.7, but I've read about issues some have had with Animator and previous Vaadin 7 versions. Is it working with 7.1.6, or some earlier 7.x version for you?

**Comment by jouni** [comment]
Tested the new 1.7.4 (coming to Vaadin Directory shortly) with Vaadin 7.1.14 and it worked as expected.

Tested with 6e62bca34b0d80df70920db62f259840d149ceda
