### ISSUE TITLE
AnimatorProxy is missing removeListener(AnimationListener)

### ISSUE THREAD

**Issue by marlonrichert** [jouni/Animator#6]
AnimatorProxy needs a removeListener(AnimationListener) method. Plus, as AnimatorProxy is a descendant of Component, AnimationListener needs to extend the Component.Listener interface, so it can be passed to Component.removeListener(Component.Listener).

**Comment by jouni** [comment]
Duplicate of #1

**Comment by marlonrichert** [comment]
Good to see I had already [discussed this with you](https://github.com/jounikoivuviita/Animator/issues/1), but too bad I failed to remember that! Oops! :P

**Comment by jouni** [comment]
Heh, no stress.

This issue was actually added by @tehapo long ago before you had created this issue (I merged the issues from an old repo to this new one).
